{
 "title": "Temperature",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Location",
    "query": "SHOW TAG VALUES WITH KEY = \"location\""
   },
   { "name": "Consigne", "query": "10" },
   { "name": "Ecart", "query": "14" },
   {
    "name": "NbHeureCreuse",
    "label": "NbHeureCreuse",
    "query": "SELECT COUNT(\"heureCreuse\") FROM \"mobilealerts\" WHERE (\"location\" = 'dehors') AND heureCreuse = 1 AND $timeFilter"
   }
  ]
 },
 "panels": [
  {
   "title": "Coût Chauffage",
   "type": "singlestat",
   "description": "Calcul du coùu du chauffage via sonde externe :\n$Consigne - Température / $Ecart * 2.5Kw * .1272€/1Wh * Nb D'Heure Creuse\nNb D'Heure Creuse = NbHeureCreuse / 8,571428571 (1H==60mm /7m separe les points )",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mobilealerts",
     "query": "SELECT ($Consigne - \"Température\" )/$Ecart * 2.5 * .1272 * $NbHeureCreuse / 8.571428571 FROM \"mobilealerts\" WHERE (\"location\" = 'dehors') AND \"Température\" < $Consigne AND $timeFilter AND heureCreuse = 1 GROUP BY heureCreuse fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Utilisation du Chauffage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Chauffage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mobilealerts",
     "query": "SELECT ($Consigne - mean(\"Température\") )/ $Ecart * 100 FROM \"mobilealerts\" WHERE ( \"location\" = 'dehors' ) AND \"Température\" < $Consigne AND heureCreuse = 1 AND $timeFilter GROUP BY time(20m) fill(null)\n\n",
     "select": [
      [
       { "params": [ "Température" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "dehors" }
     ]
    },
    {
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "% d'Utilisation du Chauffage",
   "type": "singlestat",
   "description": "Calcul du % d'utilisation du chauffage via sonde externe consigne, ecart, en heure creuse :\n\n( $Consigne - Température  ) / $Ecart * 100",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mobilealerts",
     "query": "SELECT ($Consigne - \"Température\" )/$Ecart * 100 FROM \"mobilealerts\" WHERE (\"location\" = 'dehors') AND \"Température\" < $Consigne  AND heureCreuse = 1 AND $timeFilter  fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "All Temperature",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Chambre",
     "measurement": "mobilealerts",
     "select": [
      [
       { "params": [ "Température" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "chambre" }
     ]
    },
    {
     "alias": "Cuisine",
     "measurement": "mobilealerts",
     "query": "SELECT mean(\"Température\") FROM \"mobilealerts\" WHERE (\"location\" = 'cuisine') AND $timeFilter  GROUP BY time(29m) fill(linear)",
     "select": [
      [
       { "params": [ "Température" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "cuisine" }
     ]
    },
    {
     "alias": "Antonin",
     "measurement": "mobilealerts",
     "select": [
      [
       { "params": [ "Température" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "Antonin" }
     ]
    },
    {
     "alias": "Grenier",
     "measurement": "mobilealerts",
     "query": "SELECT mean(\"Capteur de température\") FROM \"mobilealerts\" WHERE (\"location\" = 'Antonin') AND $timeFilter  GROUP BY time(29m) fill(linear)",
     "select": [
      [
       { "params": [ "Capteur de température" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "Antonin" }
     ]
    },
    {
     "alias": "Dehors",
     "measurement": "mobilealerts",
     "query": "SELECT mean(\"Température\") FROM \"mobilealerts\" WHERE (\"location\" = 'dehors') AND $timeFilter GROUP BY time(29m) fill(linear)",
     "select": [
      [
       { "params": [ "Température" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "dehors" }
     ]
    }
   ]
  },
  {
   "title": "All Hygrométrie",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "alias": "Chambre",
     "measurement": "mobilealerts",
     "query": "SELECT mean(\"Hygrométrie\") FROM \"mobilealerts\" WHERE (\"location\" = 'chambre') AND $timeFilter GROUP BY time(29m) fill(linear)",
     "select": [
      [
       { "params": [ "Hygrométrie" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "chambre" }
     ]
    },
    {
     "alias": "Cuisine",
     "measurement": "mobilealerts",
     "query": "SELECT mean(\"Hygrométrie\") FROM \"mobilealerts\" WHERE (\"location\" = 'cuisine') AND $timeFilter GROUP BY time(29m) fill(linear)",
     "select": [
      [
       { "params": [ "Hygrométrie" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "cuisine" }
     ]
    },
    {
     "alias": "Antonin",
     "measurement": "mobilealerts",
     "query": "SELECT mean(\"Hygrométrie\") FROM \"mobilealerts\" WHERE (\"location\" = 'Antonin') AND $timeFilter GROUP BY time(29m) fill(linear)",
     "select": [
      [
       { "params": [ "Hygrométrie" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "Antonin" }
     ]
    },
    {
     "alias": "Dehors",
     "measurement": "mobilealerts",
     "query": "SELECT mean(\"Hygrométrie\") FROM \"mobilealerts\" WHERE (\"location\" = 'dehors') AND $timeFilter GROUP BY time(29m) fill(linear)",
     "select": [
      [
       { "params": [ "Hygrométrie" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "dehors" }
     ]
    }
   ]
  },
  {
   "title": "$Location",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 38 },
   "repeat": "Location",
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Température",
     "measurement": "mobilealerts",
     "query": "SELECT mean(\"Température\") FROM \"mobilealerts\" WHERE (\"location\" =~ /^$Location$/) AND $timeFilter GROUP BY time(29m) fill(linear)",
     "select": [
      [
       { "params": [ "Température" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Location$/" }
     ]
    },
    {
     "alias": "Hygrométrie",
     "measurement": "mobilealerts",
     "query": "SELECT mean(\"Hygrométrie\") FROM \"mobilealerts\" WHERE (\"location\" =~ /^$Location$/) AND $timeFilter  GROUP BY time(29m) fill(linear)",
     "select": [
      [
       { "params": [ "Hygrométrie" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Location$/" }
     ]
    }
   ]
  },
  {
   "title": "Grenier",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Grenier",
     "measurement": "mobilealerts",
     "query": "SELECT mean(\"Capteur de température\") FROM \"mobilealerts\" WHERE (\"location\" = 'Antonin') AND $timeFilter  GROUP BY time(29m) fill(linear)",
     "select": [
      [
       { "params": [ "Capteur de température" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "Antonin" }
     ]
    }
   ]
  }
 ]
}