{
 "title": "Temperature v2",
 "time": { "from": "now-20d/d", "to": "now-1d/d" },
 "templating": {
  "list": [
   {
    "name": "Location",
    "query": "SHOW TAG VALUES WITH KEY = \"location\""
   },
   {
    "name": "NbHeureCreuse",
    "label": "NbHeureCreuse",
    "query": "SELECT COUNT(\"heureCreuse\") FROM \"mobilealerts\" WHERE (\"location\" = 'dehors') AND heureCreuse = 1 AND $timeFilter"
   }
  ]
 },
 "panels": [
  {
   "title": "Piscine",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Piscine",
     "measurement": "mobilealerts",
     "query": "SELECT mean(\"Température\") FROM \"mobilealerts\" WHERE (\"location\" =~ /^piscine$/) AND $timeFilter GROUP BY time(29m) fill(linear)",
     "select": [
      [
       { "params": [ "Température" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Location$/" }
     ]
    },
    {
     "alias": "Dehors",
     "measurement": "mobilealerts",
     "query": "SELECT mean(\"Température\") FROM \"mobilealerts\" WHERE (\"location\" =~ /^dehors$/) AND $timeFilter  GROUP BY time(29m) fill(linear)",
     "select": [
      [
       { "params": [ "Hygrométrie" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Location$/" }
     ]
    }
   ]
  },
  {
   "title": "% d'Utilisation du Chauffage",
   "type": "singlestat",
   "description": "Calcul du % d'utilisation du chauffage via sonde externe consigne, ecart, en heure creuse :\n\n( $Consigne - Température  ) / $Ecart * 100",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mobilealerts",
     "query": "SELECT (consigne - \"Température\" )/ecart * 100 FROM \"mobilealerts\" WHERE (\"location\" = 'dehors') AND \"Température\" < \"consigne\"  AND heureCreuse = 1 AND $timeFilter  fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Puissance Chauffage (kW/h)",
   "type": "singlestat",
   "description": "Puissance utiliser par le chauffage via sonde externe :\n$Consigne - Température / $Ecart par Heure\nNb D'Heure Creuse = NbHeureCreuse / 8,571428571 (1H==60mm /7m separe les points )",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "kwatth",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mobilealerts",
     "query": "SELECT (consigne - \"Température\" )/ecart * 2.5 * $NbHeureCreuse / 8.571428571 FROM \"mobilealerts\" WHERE (\"location\" = 'dehors') AND \"Température\" < consigne AND $timeFilter AND heureCreuse = 1 GROUP BY heureCreuse fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Coût Chauffage",
   "type": "singlestat",
   "description": "Calcul du coùu du chauffage via sonde externe :\n$Consigne - Température / $Ecart * 2.5Kw * .1272€/1Wh * Nb D'Heure Creuse\nNb D'Heure Creuse = NbHeureCreuse / 8,571428571 (1H==60mm /7m separe les points )",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mobilealerts",
     "query": "SELECT (consigne - \"Température\" )/ecart * 2.5 * 0.1272 * $NbHeureCreuse / 8.571428571 FROM \"mobilealerts\" WHERE (\"location\" = 'dehors') AND \"Température\" < consigne AND $timeFilter AND heureCreuse = 1 GROUP BY heureCreuse fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Location",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "repeat": "Location",
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Température",
     "measurement": "mobilealerts",
     "query": "SELECT mean(\"Température\") FROM \"mobilealerts\" WHERE (\"location\" =~ /^$Location$/) AND $timeFilter GROUP BY time(29m) fill(linear)",
     "select": [
      [
       { "params": [ "Température" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Location$/" }
     ]
    },
    {
     "alias": "Hygrométrie",
     "measurement": "mobilealerts",
     "query": "SELECT mean(\"Hygrométrie\") FROM \"mobilealerts\" WHERE (\"location\" =~ /^$Location$/) AND $timeFilter  GROUP BY time(29m) fill(linear)",
     "select": [
      [
       { "params": [ "Hygrométrie" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Location$/" }
     ]
    }
   ]
  },
  {
   "title": "All Temperature",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mobilealerts",
     "select": [
      [
       { "params": [ "Température" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Utilisation du Chauffage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Chauffage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mobilealerts",
     "query": "SELECT (mean(\"consigne\") - mean(\"Température\") )/ mean(\"ecart\") * 100 FROM \"mobilealerts\" WHERE \"location\" = 'dehors'  AND \"Température\" < \"consigne\" AND heureCreuse = 1 AND $timeFilter GROUP BY time(20m) fill(null)",
     "select": [
      [
       { "params": [ "Température" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "dehors" }
     ]
    },
    {
     "alias": "Max",
     "query": "SELECT (14 - mean(\"Température\") )/ 6 * 100 FROM \"mobilealerts\" WHERE \"location\" = 'dehors'  AND \"Température\" < \"consigne\" AND heureCreuse = 1 AND $timeFilter GROUP BY time(20m) fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (10 - mean(\"Température\") )/ 14 * 100 FROM \"mobilealerts\" WHERE \"location\" = 'dehors'  AND \"Température\" < \"consigne\" AND heureCreuse = 1 AND $timeFilter GROUP BY time(20m) fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "All Hygrométrie",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mobilealerts",
     "select": [
      [
       { "params": [ "Hygrométrie" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}